<div id="login-modal-content" style="display:none;">
    <form id="modal-login-form">
        <div class="field">
            <label>Email:</label>
            <input type="text" name="username" class="input-text" required/>
        </div>
        <div class="field">
            <label>Password:</label>
            <input type="password" name="password" class="input-text" required/>
        </div>
        <div class="actions">
            <button type="submit" class="action-primary">Login</button>
        </div>
    </form>
</div>
